# Dunst (executed immediately by hyprpanel)
# exec-once = /usr/bin/dunst

# NM Applet
exec-once = /usr/bin/nm-applet

# Keepassxc
exec-once = /usr/bin/keepassxc

# Polkit
exec-once = systemctl --user start hyprpolkitagent

# Waybar
# exec-once = /usr/bin/waybar
exec-once = /usr/bin/hyprpanel
